name: run ut and it

# 触发条件：当有pull_request事件发生到main分支时
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  #
  operation_before_merge:
    runs-on: ubuntu-24.04
    environment: cicd

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3  # 选择Node.js环境
        with:
          node-version: '20'  # 配置Node.js版本

      - name: Install dependencies
        run: npm install  # 针对Node.js项目安装依赖

      - name: check ut.ts file exists
        run: |
          pwd
          ls -l
          find tests -iname "*.ut.ts"


      - name: start to run ut test
        env:
          YEYING_NODE_URL: ${{ vars.YEYING_NODE_URL }}
          YEYING_AGENT_URL: ${{ vars.YEYING_AGENT_URL }}
          YEYING_WAREHOUSE_URL: ${{ vars.YEYING_WAREHOUSE_URL }}
        run: |
          echo "Using Yeying Node URL: $YEYING_NODE_URL"
          echo "Using Yeying Agent URL: $YEYING_AGENT_URL"
          echo "Using Yeying Warehouse URL: $YEYING_WAREHOUSE_URL"
          shopt -s globstar; npm run test -- tests/**/*.ut.ts

      - name: check it.ts file exists
        run: |
          pwd
          ls -l
          find tests -iname "*.ut.ts"

      - name: start to run it test
        env:
          YEYING_NODE_URL: ${{ vars.YEYING_NODE_URL }}
          YEYING_AGENT_URL: ${{ vars.YEYING_AGENT_URL }}
          YEYING_WAREHOUSE_URL: ${{ vars.YEYING_WAREHOUSE_URL }}
        run: |
          echo "Using Yeying Node URL: $YEYING_NODE_URL"
          echo "Using Yeying Agent URL: $YEYING_AGENT_URL"
          echo "Using Yeying Warehouse URL: $YEYING_WAREHOUSE_URL"
          shopt -s globstar; npm run test -- tests/**/*.it.ts


  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-24.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate docs
        run: npm run docs

      - name: check docs directory exists
        run: |
          pwd
          ls -l

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4