name: run ut and it

# 触发条件：当有pull_request事件发生到main分支时
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  #
  operation_before_merge:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3 

      - name: Set up Node.js
        uses: actions/setup-node@v3  # 选择Node.js环境
        with:
          node-version: '20'  # 配置Node.js版本

      - name: Install dependencies
        run: npm install  # 针对Node.js项目安装依赖

      - name: check ut.ts file exists
        run: |
          pwd
          ls -l
          find tests -iname "*.ut.ts"


      - name: start to run ut test
        run: shopt -s globstar; npm run test -- tests/**/*.ut.ts

      - name: check it.ts file exists
        run: |
          pwd
          ls -l
          find tests -iname "*.ut.ts"

#      - name: start to run it test
#        run: shopt -s globstar; npm run test -- tests/**/*.it.ts
