name: run ut and it

# 触发条件：当有push事件发生到main分支时
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  #
  operation_before_merge:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3  # 使用actions/checkout 仓库的 main 分支的最新提交

      - name: debug paths
        run: |
          pwd
          ls -l

      - name: Set up Node.js
        uses: actions/setup-node@v3  # 选择Node.js环境
        with:
          node-version: '20'  # 配置Node.js版本

      - name: Install dependencies
        run: npm install  # 针对Node.js项目安装依赖

      - name: set environment fo ut
        run: shopt -s globstar

      - name: start to run ts
        run: npm run test -- tests/**/*.ut.ts

      - name: check path
        run: |
          pwd
          ls -l

      - name: set environment for it
        run: shopt -s globstar

      - name: start to run it
        run: npm run test -- tests/**/*.it.ts
